name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [[ -f package-lock.json ]]; then
            npm ci
          elif [[ -f package.json ]]; then
            npm install
          else
            echo "No package.json found. Skipping dependency installation."
          fi

      - name: Run lint
        run: |
          if [[ -f package.json ]]; then
            ./scripts/lint.sh
          else
            echo "Skipping lint step because package.json is missing."
          fi

      - name: Run tests
        run: |
          if [[ -f package.json ]]; then
            ./scripts/test.sh
          else
            echo "Skipping test step because package.json is missing."
          fi
